dist: bionic
language: python
python:
  - "3.8"

install:
  - pip install nbfancy

script:
  - nbfancy render
  - nbfancy html --include_slides --redirect 00_homepage.html

deploy:
  provider: pages
  repo: excalibur-genx/excalibur-genx.github.io
  target-branch: gh-pages
  local-dir: html
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master
    python: 3.8
